apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v0i07slpe-go 
  janus-idp.io/tekton: v0i07slpe-go
  backstage.io/kubernetes-id: v0i07slpe-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v0i07slpe-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml